export const NOTES_FETCH_REQUEST = "NOTES_FETCH_REQUEST"
export const NOTES_FETCH_SUCCESS = "NOTES_FETCH_SUCCESS"
export const NOTES_FETCH_FAIL = "NOTES_FETCH_FAIL"
export const NOTES_FETCH_RESET = "NOTES_FETCH_RESET"

export const NOTES_ADD_REQUEST = "NOTES_ADD_REQUEST"
export const NOTES_ADD_SUCCESS = "NOTES_ADD_SUCCESS"
export const NOTES_ADD_FAIL = "NOTES_ADD_FAIL"
export const NOTES_ADD_RESET = "NOTES_ADD_RESET"

export const NOTES_DELETE_REQUEST = "NOTES_DELETE_REQUEST"
export const NOTES_DELETE_SUCCESS = "NOTES_DELETE_SUCCESS"
export const NOTES_DELETE_FAIL = "NOTES_DELETE_FAIL"
export const NOTES_DELETE_RESET = "NOTES_DELETE_RESET"
